from plotting_functions import plot1d, plot2d
import matplotlib.pyplot as plt
import os

# This script is used to plot the results of the AeoLiS model
# The functions plot1d and plot2d are defined in the plotting_functions.py file
# Using this script as a template, you can easily start plotting some basic results generated by the AeoLiS model

# Get the path to the netcdf-file containing the results of the AeoLiS model run
# This is relative to the location of the current script
ncfile = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'aeolis_output.nc')	


############################################################################################################
# The function plot2d is used to plot 2D results of the AeoLiS model

# - ncfile: path to the netcdf-file containing the results of the AeoLiS model run
# - itimes: index of the time step to plot (default: 0)
# - ifrac: grainfraction to plot (default: 0)
# - param: parameter to plot (default: 'zb')
# - cmap: colormap to use (default: plt.cm.jet)
# - clim: color limits [min, max], or 'auto' will automatically determine the color limits (default: 'auto')
# - delta: plot the difference between the current and previous time step (default: False)
# - itimeDelta: time step difference (default: -1), only used if delta=True

# Plot the bed level at the first time step
fig, ax = plot2d(ncfile)
ax.set_title('Bed level at the first time step')

# Plot the bed level at the last time step
fig, ax = plot2d(ncfile, param='zb', itimes=-1)
ax.set_title('Bed level at the last time step')

# Plot the bed level at the first time step with a different colormap and color limits
fig, ax = plot2d(ncfile, param='zb', itimes=0, delta=True, itimeDelta=-1, cmap=plt.cm.RdBu, clim=[-1.5, 1.5])
ax.set_title('Bed level change between the first and last time step with custom colormap and color limits')

# Plot the wind velocity at the last timestep using the viridis colormap
fig, ax = plot2d(ncfile, param='uw', itimes=-1, cmap=plt.cm.viridis)
ax.set_title('Wind velocity at the last time step')

# Plot the velocity threshold at the last timestep only for the 1st fraction
fig, ax = plot2d(ncfile, param='uth', itimes=-1, ifrac=0, clim=[0, 0.4])
ax.set_title('Velocity threshold at the last time step for the 1st fraction')


############################################################################################################
# The function plot1d is used to plot 1D results of the AeoLiS model of a single transect
# Timesteps, transects and parameters can be given as a list to plot multiple results at once

# - ncfile: path to the netcdf-file containing the results of the AeoLiS model run
# - itransects: index of the transect to plot (default: 0)
# - itimes: index of the time step to plot (default: 0)
# - ifrac: grainfraction to plot (default: 0)
# - params: list of parameters to plot (default: ['zb'])

# Plot the bed level and water level at the first transect and last timestep
fig, ax = plot1d(ncfile, itransects=0, itimes=-1, ifrac=0, params=['zb', 'zs'])
ax.set_title('Bed level and water level at the first transect and last timestep')

# Plot the bed level at the first, middle and last timestep for the first transect
fig, ax = plot1d(ncfile, itransects=0, itimes=[0, 4, -1], ifrac=0, params='zb')
ax.set_title('Bed level at the first, middle and last timestep for the first transect')

# Plot the bed level for the first and last transect at the last timestep
fig, ax = plot1d(ncfile, itransects=[0, -1], itimes=-1, ifrac=0, params='zb')
ax.set_title('Bed level for the first and last transect at the last timestep')

plt.show()